# Decap CMS Configuration File
# Settings will be added in subsequent tasks.

backend:
  name: git-gateway
  # The Netlify Auth0 extension handles authenticating the user
  # and should make that user available to Git Gateway.
  branch: main # Or your primary branch

# Media and Collections will remain as previously planned
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "Home"
    label: "Home"
    folder: "content/home"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        type: "text"
